INSERT INTO Businesses (id, name, description, price_level) VALUES (1, '10 Barrel Brewing Co', 'Sprawling brewpub serving several house beers alongside inventive pizzas, burgers & bar snacks.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (2, '1515 Restaurant', 'The New American menu focuses on modern, sophisticated preparations at this warm, loungey option.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (3, '801 Chop House', 'Prime cuts of beef, seafood & a large wine selection offered in an elegant, clubby setting.', 4);
INSERT INTO Businesses (id, name, description, price_level) VALUES (4, 'Adelitas Cocina Y Catina', 'Festive restaurant offering Mexican food with a Michoacán bent, craft cocktails & weekend brunch.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (5, 'Adrift Tiki Bar', 'Tropical-themed tiki bar offering rum-centric, island-style drinks plus Polynesian-inspired bites.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (6, 'Aloy Thai', 'Contemporary Thai fare, complemented by craft beer, wine & cocktails, served in stylish surrounds.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (7, 'Atticus', 'Vintage-vibe find serving eclectic cafe fare (from burritos to spaetzle), coffee & cocktails.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (8, 'Bad Daddy''s Burger Bar', 'Hip, buzzy chain serving creative burgers with gourmet toppings, plus hand-cut fries & other sides.', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (9, 'Bar Dough', 'Modern-rustic Italian spot featuring gourmet wood-fired pizzas, plus pastas, wine, beer & cocktails.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (10, 'Biju''s Little Curry Shop', 'Curry dishes dominate the menu at this Indian spot with compact quarters & brightly hued decor.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (11, 'Billy''s Inn', 'Bar & grill with American & Mexican grub & period architecture reflecting its circa-1933 premiere.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (12, 'Blackbird Public House', 'Eatery boasting a gourmet menu of global eats, plus cocktails, wine, shuffleboard & flat-screen TVs.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (13, 'Blue Island Oyster Bar', 'Polished seafood restaurant featuring a raw bar, beer & craft cocktails in nautical surrounds.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (14, 'Blueprint Bar', 'This restaurant is permanently closed. Architectural accents pepper the loungey decor at this laid-back Uptown sibling to DiFranco''s, where cocktails both classic and original accompany New American small plates with Mediterranean flair.', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (15, 'Brider', 'All-day American spot serving roasted meats, craft beer & cocktails in modern, counter-serve digs.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (16, 'Brodo Italian Scratch Kitchen', 'Pasta, chicken Parm & other Italian favorites served in a colorful, contemporary setting.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (17, 'Broken Rice', 'Pan Asian–style noodles, soups, rice bowls & more in a bright, modern cafe with counter service.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (18, 'bubu', 'Customizable bowls featuring veggies, grains, housemade dressings & an assortment of toppings.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (19, 'BurgerFi', 'Stylish, eco-minded chain serving grass-fed beef burgers, plus hot dogs, craft beer & wine.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (20, 'Butcher''s Bistro', 'Locally sourced meat is on offer raw, in housemade sausages or prepared at this narrow locale.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (21, 'Candela Latin Kitchen', 'Empanadas & tacos, margaritas & sangria await at this hip, hopping Pan-Latin kitchen/bar.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (22, 'CHUBurger', 'Funky counter joint serving burgers & craft brews, plus coffee & donuts on the side.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (23, 'Corner Office', 'Modern takes on comfort classics that span the globe plus cocktails in a sleek setting.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (24, 'Crafty Fox', 'Lively 2-story hangout with a huge craft beer list, plus innovative pizzas, games & patio seating.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (25, 'Denver Deep Dish', 'Family-friendly pizzeria slinging Chicago-style pies, plus salads, sandwiches & more.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (26, 'Departure Denver Restaurant + Lounge', 'Playful plates & cocktails inspired by Asia''s culinary traditions served against a splashy backdrop.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (27, 'DiFranco''s', 'Quaint locavore cafe specializing in old-world fare with seasonal ingredients & freshly made pastas.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (28, 'Dos Santos', 'Innovative Mexican fare, beer & craft cocktails served in industrial, wood-accented digs.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (29, 'El Jefe Denver', 'Stylish, coastal-inspired Mexican eatery serving up gourmet seafood, tacos, margaritas & more.  ', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (30, 'Element Kitchen', 'This second-floor hideaway serves up drinks & snacks while also selling collectible athletic shoes.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (31, 'Esters', 'Laid-back place features eclectic pizza & large selection of craft beers, plus special guest brews.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (32, 'Fish N Beer', 'Oysters, grilled fish & creative seafood plates in a tiny, retro-toned space with a full bar.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (33, 'FNG', 'Down-home, but elevated fare from a modern bar & grill with a rock ''n'' roll motif, bar & patio.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (34, 'Gaetano''s', 'Founded by a mob family, this colorful icon serves classic Italian dishes & creative cocktails.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (35, 'Go Fish Sushi', 'No-frills Japanese corner cafe with classics such as sushi & tempura, plus a wine & sake selection.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (36, 'Grind Kitchen + Watering Hole', 'Intimate, garden-level spot with a New American menu plus craft cocktails, housemade sodas & beer.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (37, 'Hashtag', 'Colorful chef-driven breakfast joint serving up eggs, hash & hotcakes in wide array, plus cocktails.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (38, 'Highland Tap and Burger', 'Lively bar & grill serving gourmet burgers & local microbrews in TV-filled digs with a patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (39, 'Hopdoddy Burger Bar', 'Sleek setting for craft brew & extra-large burgers topped high with indulgent ingredients.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (40, 'Humboldt Farm Fish Wine', 'Market-fresh & fish-centric New American menu, with oysters & craft beer, in an urban-chic locale.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (41, 'Ignite Kitchen + Cocktails', 'Trendy eatery known for gourmet burgers & other rustic dishes as well as its cozy roof patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (42, 'Ink! Coffee', 'Local counter chain link with a mod-industrial vibe, house-roasted coffees & simple daytime menu.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (43, 'Jack''s Uptown Grille', 'Casually classy neighborhood spot with a patio serving traditional American eats, including burgers.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (44, 'Jax Fish House Glendale', 'Upscale chain serving gourmet seafood dishes & creative cocktails in a relaxed, stylish setting.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (45, 'Jett Asian Kitchen & Sushi Bar', 'Casual Pan-Asian eatery known for modern interpretations of classic Chinese, Thai & Japanese dishes.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (46, 'Kachina Cantina', 'Frybread, bison & other Southwestern specialties star on the menu of this lively eatery & bar.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (47, 'La Sandia Cantina', 'Mexican comfort food & huge tequila selection in a modern setting with outdoor patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (48, 'Lena', 'Latin American-inspired bites including wood-fired meats & small plates plus cocktails, beer & wine.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (49, 'Lime', '500 16th St #322, Denver, CO 80202', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (50, 'Little India', 'Tandoori specials, assorted Indian favorites & an all-you-can-eat lunch buffet in sleek surrounds.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (52, 'Little India Champa Downtown', 'Tandoori specials, assorted Indian favorites & an all-you-can-eat lunch buffet in sleek surrounds.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (53, 'Lo Stella Ristorante', 'Family-run Italian eatery serving fresh pasta, pizza & traditional dishes in a relaxed atmosphere.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (54, 'LoHi Steakbar', 'Sleek, happening hangout serving prime cuts of meat & steakhouse standards with custom cocktails.', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (55, 'Lola Coastal Mexican', 'Highbrow Mexican cuisine & imaginative drinks fuel the bustling scene at this cantina with a patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (56, 'Los Chingones', 'Bi-level Mexican eatery & lounge boasting a menu of innovative bites & a terrace with skyline views.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (57, 'Los Chingones Mexican DTC', 'Edgy, graffiti-splashed Mexican eatery & lounge boasting a raw bar, innovative cocktails & a patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (58, 'Low Country Kitchen', 'Fried chicken, bourbon cocktails & other Southern treats star at this homey spot with a roof deck.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (59, 'Lucky Pie Pizza & Taphouse', 'Artisanal pizza & other inventive, organic snacks plus craft suds served in bright quarters.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (60, 'Marco''s Coal Fired Pizzeria', 'Neapolitan pizzas handmade from imported Italian ingredients in rustic brick digs with a patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (61, 'Marg''s Taco Bistro', 'Tacos take on global overtones at this hip, modern hangout, which also pours funky margaritas.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (62, 'Max''s Wine Dive', 'Wine bar serving Southern-inspired New American eats in a boisterous setting with a busy happy hour.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (63, 'Mizu Izakaya', 'Artsy Japanese tavern serving yakitori, sushi & other small bites with sake, beer & cocktails.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (64, 'Modern Market', 'Sleek, counter-serve cafe for health-conscious salads & sandwiches, including vegan options.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (65, 'North County', 'Bright setting for street & Baja-style Mexican eats such as tacos & po'' boys amid beachy decor.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (66, 'Olive & Finch', 'Warm market & bistro with coffee bar & menu of pastries & sandwiches, plus to-go eats, beer & wine', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (67, 'Onefold', 'Quaint, farmhouse-style haunt serving coffee, baked goods & creative cafe fare with global touches.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (68, 'Park Burger', 'Understated, dinerlike corner spot dishing up imaginative twists on burgers, plus fries & more.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (69, 'PokeCity', 'Made-to-order Hawaiian poke bowls with many toppings turned out in modern, counter-serve digs.', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (70, 'Prohibition', 'Classic & contemporary cocktails poured in a 1920s-inspired tavern with exposed brick.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (71, 'range', 'Craft cocktails, local brews & a frontier-inspired menu are served in a chic, saloonlike space.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (72, 'Recess Beer Garden', 'Craft beer & American grub served in casual digs with a large patio featuring picnic tables & games.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (73, 'Revelry Kitchen', 'American breakfast & lunch dishes, plus cocktails, served in airy digs with a patio.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (74, 'Scratch Burrito', 'Rustic-chic bar/eatery preparing burritos, wings & other American finger foods with a gourmet twist.', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (75, 'Shells & Sauce', 'Jazzy little trattoria serving classic & creative fare, plus brunch & happy hour on the roof deck.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (76, 'Ship Tavern', 'This swanky pub, a Brown Palace Hotel staple since 1934, serves up steak, live piano & TV sports.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (77, 'STK', 'Sleek, clubby link in a national chain serving modern chophouse eats & drinks with a side of scene.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (78, 'Sushi Hai', 'Funky Japanese go-to decorated by local artists includes a 3,000-sq.-ft. martini & sushi lounge.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (79, 'Sushi Ronin', 'Japanese eatery & bar featuring artistic presentations of fresh fish in stylish, modern surrounds.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (80, 'Tacos Tequila Whiskey', 'Innovative street-style tacos (such as tongue & pork belly) & cocktails in a packed setting.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (81, 'TAG Burger Bar', 'Informal bar & grill with an inventive menu of hamburgers, sweet treats, craft brews & cocktails.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (82, 'Tamayo', 'Innovative Mexican plates come out of the kitchen of this chic spot with a vast rooftop deck.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (83, 'Tap & Burger Sloan''s Lake', 'Local beer, gourmet burgers & other modern bar food in slick, roomy digs lined with flat-screens.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (84, 'The Avenue Grill', 'White-tablecloth supper club serving San Francisco-style fare & martinis, plus late-night bites.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (85, 'The Berkshire', 'Pig is the star at this trendy, rustic American restaurant focused on innovative pork preparations.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (86, 'The Cherry Tomato', 'Busy neighborhood Italian eatery with tablecloths kids can color on & a sizable wine list', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (87, 'The Lobby', 'Restaurant & bar serving American comfort fare in a historic building with a courtyard patio.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (88, 'The Pig & The Sprout', 'Contemporary American eats & drinks in a high-energy, bi-level space with multiple bars.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (89, 'The Rosedale', 'Burgers, wings & oysters, plus craft beer & cocktails, served in a cheerful tavern environment.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (90, 'The Wooden Table', 'Seasonal Italian fare served in an upscale trattoria with minimalist, stylish environs.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (91, 'There', 'Globally inspired dishes & clever cocktails abound at this watering hole with a bohemian vibe.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (92, 'Tupelo Honey', 'Lively outpost of a Southern franchise serving up fried chicken, po'' boys, mint juleps & more.', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (93, 'Uno Mas Taqueria', 'Modern Mexican eatery & bar offering street-style tacos made with house-grown & local ingredients.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (94, 'Urban Farmer Denver', 'Colorful yet sleek contemporary chophouse with a focus on sustainability in The Oxford Hotel.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (95, 'White Pie', 'Oak-fired pizzas supplemented by seasonal Italian dishes star at this casually stylish parlor.', 1);

