INSERT INTO Businesses (id, name, description, price_level) VALUES (1, '10 Barrel Brewing Co', 'Sprawling brewpub serving several house beers alongside inventive pizzas, burgers & bar snacks.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (2, '1515 Restaurant', 'The New American menu focuses on modern, sophisticated preparations at this warm, loungey option.', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (3, '801 Chop House', 'Prime cuts of beef, seafood & a large wine selection offered in an elegant, clubby setting.', 4);
INSERT INTO Businesses (id, name, description, price_level) VALUES (4, 'Adelitas Cocina Y Catina', 'Festive restaurant offering Mexican food with a Michoacán bent, craft cocktails & weekend brunch.', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (5, 'Adrift Tiki Bar', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (6, 'Aloy Thai', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (7, 'Atticus', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (8, 'Bad Daddy''s Burger Bar', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (9, 'Bar Dough', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (10, 'Biju''s Little Curry Shop', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (11, 'Billy''s Inn', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (12, 'Blackbird Public House', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (13, 'Blue Island Oyster Bar', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (14, 'Blueprint Bar', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (15, 'Brider', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (16, 'Brodo Italian Scratch Kitchen', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (17, 'Broken Rice', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (18, 'bubu', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (19, 'BurgerFi', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (20, 'Butcher''s Bistro', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (21, 'Candela Latin Kitchen', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (22, 'CHUBurger', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (23, 'Corner Office', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (24, 'Crafty Fox', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (25, 'Denver Deep Dish', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (26, 'Departure Denver Restaurant + Lounge', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (27, 'DiFranco''s', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (28, 'Dos Santos', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (29, 'El Jefe Denver', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (30, 'Element Kitchen', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (31, 'Esters', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (32, 'Fish N Beer', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (33, 'FNG', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (34, 'Gaetano''s', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (35, 'Go Fish Sushi', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (36, 'Grind Kitchen + Watering Hole', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (37, 'Hashtag', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (38, 'Highland Tap and Burger', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (39, 'Hopdoddy Burger Bar', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (40, 'Humboldt Farm Fish Wine', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (41, 'Ignite Kitchen + Cocktails', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (42, 'Ink! Coffee', 'testing 1234', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (43, 'Jack''s Uptown Grille', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (44, 'Jax Fish House Glendale', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (45, 'Jett Asian Kitchen & Sushi Bar', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (46, 'Kachina Cantina', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (47, 'La Sandia Cantina', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (48, 'Lena', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (49, 'Lime', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (50, 'Little India', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (51, 'Little India 6th Avenue', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (52, 'Little India Champa Downtown', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (53, 'Lo Stella Ristorante', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (54, 'LoHi Steakbar', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (55, 'Lola Mexican Fish House', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (56, 'Los Chingones', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (57, 'Los Chingones Mexican DTC', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (58, 'Low Country Kitchen', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (59, 'Lucky Pie Pizza & Taphouse', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (60, 'Marco''s Coal Fired Pizzeria', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (61, 'Marg''s Taco Bistro', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (62, 'Max''s Wine Dive', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (63, 'Mizu Izakaya', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (64, 'Modern Market', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (65, 'North County', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (66, 'Olive & Finch', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (67, 'Onefold', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (68, 'Park Burger', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (69, 'PokeCity', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (70, 'Prohibition', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (71, 'range', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (72, 'Recess Beer Garden', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (73, 'Revelry Kitchen', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (74, 'Scratch Burrito', 'TBD', 0);
INSERT INTO Businesses (id, name, description, price_level) VALUES (75, 'Shells & Sauce', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (76, 'Ship Tavern', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (77, 'STK', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (78, 'Sushi Hai', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (79, 'Sushi Ronin', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (80, 'Tacos Tequila Whiskey', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (81, 'TAG Burger Bar', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (82, 'Tamayo', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (83, 'Tap & Burger Sloan''s Lake', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (84, 'The Avenue Grill', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (85, 'The Berkshire', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (86, 'The Cherry Tomato', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (87, 'The Lobby', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (88, 'The Pig & The Sprout', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (89, 'The Rosedale', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (90, 'The Wooden Table', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (91, 'There', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (92, 'Tupelo Honey', 'TBD', 2);
INSERT INTO Businesses (id, name, description, price_level) VALUES (93, 'Uno Mas Taqueria', 'TBD', 1);
INSERT INTO Businesses (id, name, description, price_level) VALUES (94, 'Urban Farmer Denver', 'TBD', 3);
INSERT INTO Businesses (id, name, description, price_level) VALUES (95, 'White Pie', 'TBD', 1);

