INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (1, 2, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (2, 2, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (3, 4, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (4, 4, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (5, 5, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (6, 5, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (7, 6, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (8, 6, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (9, 7, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (10, 7, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (11, 8, 'Buy Signature Cocktail or Draft Beer, Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (12, 8, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (23, 9, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (24, 9, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (26, 10, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (29, 11, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (30, 11, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (31, 12, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (32, 12, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (33, 13, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (34, 13, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (35, 14, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (36, 14, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (37, 15, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (38, 15, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (39, 16, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (40, 16, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (41, 17, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (42, 17, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (46, 18, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (47, 19, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (48, 19, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (49, 20, 'Buy 1 Drink Get 1 Free', 'Up to $10. Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (50, 20, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (51, 21, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (52, 21, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (53, 22, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (54, 22, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (56, 23, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (57, 24, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (58, 24, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (59, 25, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (60, 25, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (62, 26, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (63, 27, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (64, 27, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (65, 28, 'Buy 1 House Margarita Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (66, 28, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (67, 29, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (68, 29, 'Buy 1 Entree Get 1 Free', 'Up to $20', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (69, 30, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (70, 30, 'Buy 1 Entree Get 1 Free', 'Up to $20', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (72, 31, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (73, 32, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (74, 32, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (76, 33, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (77, 34, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (78, 34, 'Buy 1 Entree Get 1 Free', 'Dinner Only', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (79, 35, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (80, 35, 'Buy 1 Sushi Roll Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (81, 36, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (82, 36, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (84, 37, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (85, 38, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (86, 38, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (87, 39, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase after 1:30pm', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (88, 39, 'Buy 1 Entree Get 1 Free', 'Valid after 1:30pm', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (90, 40, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (92, 41, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (93, 43, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (94, 43, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (95, 44, 'Buy 1 Drink Get 1 Free', 'Brunch Only. Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (96, 44, 'Buy 1 Entree Get 1 Free', 'Brunch Only. Not valid for bottomless crab', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (97, 45, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (98, 45, 'Buy 1 Sushi Roll Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (100, 46, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (101, 47, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (102, 47, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (103, 48, 'Buy 1 House Margarita or Sangria Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (104, 48, 'Buy 1 Lunch Entree Get 1 Free OR Buy 1 Taco Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (105, 49, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (106, 49, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (107, 50, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (108, 50, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (115, 51, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (116, 51, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (117, 52, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (118, 52, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (119, 53, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (120, 53, 'Buy 1 Salad, Pasta, or Pizza Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (121, 54, 'Buy 1 Signature Cocktail Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (122, 54, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (123, 55, 'Buy 1 Silver Coin Margarita Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (124, 55, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (130, 56, 'Buy 1 Entree Get 1 Free', 'One deal per visit', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (132, 57, 'Buy 1 Entree Get 1 Free', 'One deal per visit', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (133, 58, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (134, 58, 'Buy 1 5-Piece Fried Chicken Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (135, 59, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (136, 59, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (138, 60, 'Buy 1 Pizza Get 1 Marghertia Pizza Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (139, 61, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (140, 61, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (141, 62, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (142, 62, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (143, 63, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (144, 63, 'Buy 1 Sushi Roll Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (158, 64, 'Buy 1 Entree Get 1 Free', 'Code: DPB', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (159, 65, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (160, 65, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (161, 66, 'Buy 1 Drink Get 1 Free', 'Valid with $10 purchase excluding tax and gratuity', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (162, 66, 'Buy 1 Entree Get 1 Free', 'Not valid between 10am-3pm', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (163, 67, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (164, 67, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (171, 68, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (172, 68, 'Buy 1 Burger Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (175, 69, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (176, 69, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (177, 70, 'Buy 1 Draft Beer Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (178, 70, 'Buy 1 Sandwich Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (179, 71, 'Buy 1 Drink Get 1 Free', 'Valid only with entree purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (180, 71, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (181, 72, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (182, 72, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (184, 73, 'Buy 1 Entree Get 1 Free', 'Not valid during special events', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (185, 74, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (186, 74, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (188, 75, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (190, 76, 'Buy 1 Entree Get 1 Free', 'Up to $25', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (191, 77, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (192, 77, 'Buy 1 Entree Get 1 Free', 'Up to $35', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (194, 78, 'Buy 1 Sushi Roll Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (196, 79, 'Buy 1 Sushi Roll Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (201, 80, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (202, 80, 'Buy 1 Taco Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (204, 81, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (205, 82, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase.  Not valid during Saturday or Sunday brunch', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (206, 82, 'Buy 1 Entree Get 1 Free', 'Not valid during Saturday or Sunday brunch', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (207, 83, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (208, 83, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (209, 84, 'Buy 1 Drink Get 1 Free', 'Up to $10. Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (210, 84, 'Buy 1 Entree Get 1 Free', 'Up to $20', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (211, 85, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (212, 85, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (213, 86, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (214, 86, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (215, 87, 'Buy 1 Drink Get 1 Free', 'Not Valid on Saturday or Sunday brunch or bottlemless drinks Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (216, 87, 'Buy 1 Entree Get 1 Free', 'Not Valid on Saturday or Sunday brunch', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (217, 88, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (218, 88, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (219, 89, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (220, 89, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (221, 90, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (222, 90, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (223, 91, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (224, 91, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (225, 92, 'Buy 1 Drink Get 1 Free', 'Up to $10. Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (226, 92, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (229, 93, 'Buy 1 House Margarita or Draft beer Get the Second One Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (230, 93, 'Buy 1 Taco Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (232, 94, '$25 off Total Bill', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (233, 95, 'Buy 1 Cocktail Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (234, 95, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (235, 1, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (236, 1, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (237, 3, 'Buy 1 Drink Get 1 Free', 'Valid only with food purchase', 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (238, 3, 'Buy 1 Entree Get 1 Free', 'Up to $35', 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (239, 42, 'One Free Coffee Drink', 'With any purchase', 'Drink');
