INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (1, '10 Barrel Brewing Co', null, 'http://10barrel.com/pub/denver', '4.5', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (2, '1515 Restaurant ', null, 'http://www.1515restaurant.com/', '4.3', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (3, '801 Chop House', null, 'https://801chophouse.com/denver/', '3.7', 4);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (4, 'Adelitas Cocina Y Catina', null, 'http://www.adelitasdenver.com/?utm_source=local&utm_medium=organic&utm_campaign=gmb', '4.5', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (5, 'Adrift Tiki Bar', null, 'http://adriftbar.com/', '4.3', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (6, 'Aloy Thai', null, 'http://www.aloythai.com/', '4.2', 0);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (7, 'Atticus', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (8, 'Bad Daddy''s Burger Bar', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (9, 'Bar Dough', null, 'http://bardoughdenver.com/', '4.4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (10, 'Biju''s Little Curry Shop', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (11, 'Billy''s Inn', null, 'http://www.billysinn.com/', '4.3', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (12, 'Blackbird Public House', null, 'http://blackbirdpublichouse.com/', '4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (13, 'Blue Island Oyster Bar', null, 'https://www.blueislandoysterbar.com/', '4.5', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (14, 'Blueprint Bar', null, 'None', '4.5', 0);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (15, 'Brider', null, 'http://www.denverbrider.com/', '4.4', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (16, 'Brodo Italian Scratch Kitchen', null, 'http://brodoscratchkitchen.com/', '3.7', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (17, 'Broken Rice', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (18, 'bubu', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (19, 'BurgerFi', null, 'https://burgerfi.com/?utm_source=local&utm_medium=snack_pack&utm_campaign=co&utm_content=denver&utm_term=410152', '4.1', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (20, 'Butcher''s Bistro', null, 'http://www.thebutchersbistro.com/', '4.6', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (21, 'Candela Latin Kitchen', null, 'http://www.candeladenver.com/', '4.3', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (22, 'CHUBurger', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (23, 'Corner Office', null, 'http://www.thecornerofficedenver.com/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (24, 'Crafty Fox', null, 'http://www.craftyfox.beer/', '4.3', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (25, 'Denver Deep Dish ', null, 'http://www.denverdeepdish.com/', '3.8', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (26, 'Departure', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (27, 'DiFranco''s', null, 'http://www.difrancos.com/', '4.6', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (28, 'Dos Santos', null, 'http://www.dossantosdenver.com/?utm_source=local&utm_medium=organic&utm_campaign=gmb', '4.2', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (29, 'El Jefe', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (30, 'Element Kitchen', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (31, 'Esters', null, 'http://www.estersdenver.com/', '4.7', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (32, 'Fish N Beer', null, 'http://fishnbeerdenver.com/', '4.7', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (33, 'FNG', null, 'http://fngrestaurant.com/', '4.5', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (34, 'Gaetano''s', null, 'http://www.gaetanositalian.com/?utm_source=local&utm_medium=organic&utm_campaign=gmb', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (35, 'Go Fish', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (36, 'Grind Kitchen + Watering Hole', null, 'http://grinddenver.com/', '4.3', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (37, 'Hashtag', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (38, 'Highland Tap & Burger', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (39, 'Hopdoddy Burger Bar', null, 'http://www.hopdoddy.com/', '4.4', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (40, 'Humboldt Farm Fish Wine', null, 'https://humboldtrestaurant.com/', '4.4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (41, 'Ignite Kitchen + Cocktails', null, 'https://www.ignite-denver.com/?utm_source=local&utm_medium=organic&utm_campaign=gmb', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (42, 'Ink! Coffee', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (43, 'Jack''s Update Grille', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (44, 'Jax Fish House Glendale', null, 'http://www.jaxfishhouse.com/glendale', '4.3', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (45, 'Jett Asian Kitchen & Sushi Bar', null, 'http://www.jettasiankitchendenver.com/', '4.1', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (46, 'Kachina', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (47, 'La Sandia', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (48, 'Lena', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (49, 'Lime', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (50, 'Little India 6th Avenue', null, 'https://www.littleindiaofdenver.com/locations/330-east-6th-avenue/', '3.9', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (51, 'Little India LoDo', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (52, 'Lo Stella Ristorante', null, 'http://www.lostelladenver.com/?utm_source=GMBlisting&utm_medium=organic', '4.6', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (53, 'LoHi Steakbar', null, 'http://www.lohisteakbar.com/', '4.1', 0);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (54, 'Lola Mexican Fish House', null, 'http://www.loladenver.com/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (55, 'Los Chingones', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (56, 'Low Country Kitchen', null, 'https://lowrestaurant.com/', '4.3', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (57, 'Lucky Pie', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (58, 'Marco''s Coal Fired Pizzeria', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (59, 'Marg''s Taco Bistro', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (60, 'Max''s Wine Dive', null, 'https://www.maxswinedive.com/denver/menu/', '4.5', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (61, 'Mizu Izakaya', null, 'http://www.mizudenver.com/', '4.4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (62, 'Modern Market', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (63, 'North County', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (64, 'Olive & Finch', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (65, 'Onefold', null, 'http://onefolddenver.com/', '4.5', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (66, 'Park Burger', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (67, 'PokeCity', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (68, 'Prohibition', null, 'http://www.prohibitiondenver.com/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (69, 'range', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (70, 'Recess Beer Garden', null, 'http://recessbeergarden.com/', '4.4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (71, 'Revelry Kitchen', null, 'http://www.revelrydenver.com/', '4.2', 1);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (72, 'Scratch Burrito', null, 'http://scratchburrito.com/', '4.5', 0);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (73, 'Shells & Sauce', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (74, 'Ship Tavern', null, 'https://www.brownpalace.com/dining/restaurants/shiptavern', '3.6', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (75, 'STK', null, 'http://togrp.com/venue/stk-denver/', '4.1', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (76, 'Sushi Hai', null, 'http://www.sushihaidenverco.com/', '4.1', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (77, 'Sushi Ronin', null, 'http://www.sushironindenver.com/', '4.4', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (78, 'Tacos Tequila Whiskey', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (79, 'TAG Burger Bar', null, 'http://tagburgerbar.com/', '4.4', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (80, 'Tamayo', null, 'http://www.eattamayo.com/', '4.1', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (81, 'Tap & Burger at Sloan''s Lake', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (82, 'The Avenue Grill', null, 'http://www.avenuegrill.com/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (83, 'The Berkshire', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (84, 'The Cherry Tomato', null, 'https://cherrytomatodenver.com/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (85, 'The Lobby', null, 'http://www.thelobbydenver.com/?utm_source=GMBlisting&utm_medium=organic', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (86, 'The Pig & The Sprout', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (87, 'The Rosedale', null, 'http://therosedaledenver.com/', '3.9', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (88, 'The Wooden Table', null, 'http://www.thewoodentablerestaurant.com/?utm_source=GMBlisting&utm_medium=organic', '4.2', 3);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (89, 'There', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (90, 'Tupelo Honey', null, 'https://tupelohoneycafe.com/location/denver/', '4.2', 2);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (91, 'Uno Mas Taqueria', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (92, 'Urban Farmer', null, null, null, null);
INSERT INTO Businesses (id, name, description, website, google_rating, price_level) VALUES (93, 'White Pie', null, 'http://whitepiedenver.com/?utm_source=local&utm_medium=organic&utm_campaign=gmb', '4.6', 1);

INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (1, 1, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (2, 1, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (3, 2, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (4, 2, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (5, 3, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (6, 3, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (7, 4, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (8, 4, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (9, 5, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (10, 5, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (11, 6, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (12, 6, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (13, 9, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (14, 9, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (15, 11, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (16, 11, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (17, 12, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (18, 12, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (19, 13, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (20, 13, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (21, 14, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (22, 14, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (23, 15, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (24, 15, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (25, 16, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (26, 16, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (27, 19, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (28, 19, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (29, 20, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (30, 20, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (31, 21, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (32, 21, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (33, 23, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (34, 23, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (35, 24, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (36, 24, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (37, 25, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (38, 25, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (39, 27, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (40, 27, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (41, 28, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (42, 28, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (43, 31, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (44, 31, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (45, 32, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (46, 32, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (47, 33, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (48, 33, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (49, 34, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (50, 34, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (51, 36, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (52, 36, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (53, 39, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (54, 39, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (55, 40, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (56, 40, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (57, 41, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (58, 41, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (59, 44, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (60, 44, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (61, 45, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (62, 45, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (63, 50, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (64, 50, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (65, 52, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (66, 52, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (67, 53, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (68, 53, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (69, 54, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (70, 54, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (71, 56, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (72, 56, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (73, 60, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (74, 60, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (75, 61, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (76, 61, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (77, 65, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (78, 65, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (79, 68, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (80, 68, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (81, 70, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (82, 70, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (83, 71, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (84, 71, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (85, 72, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (86, 72, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (87, 74, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (88, 74, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (89, 75, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (90, 75, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (91, 76, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (92, 76, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (93, 77, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (94, 77, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (95, 79, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (96, 79, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (97, 80, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (98, 80, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (99, 82, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (100, 82, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (101, 84, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (102, 84, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (103, 85, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (104, 85, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (105, 87, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (106, 87, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (107, 88, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (108, 88, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (109, 90, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (110, 90, 'Buy 1 Entree Get 1 Free', null, 'Food');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (111, 93, 'Buy 1 Drink Get 1 Free', null, 'Drink');
INSERT INTO Coupons (id, bus_id, description, restrictions, coup_type) VALUES (112, 93, 'Buy 1 Entree Get 1 Free', null, 'Food');

INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (1, 1, 'S', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (2, 1, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (3, 1, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (4, 1, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (5, 1, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (6, 1, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (7, 1, 'S', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (8, 2, 'Su', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (9, 2, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (10, 2, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (11, 2, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (12, 2, 'Tr', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (13, 2, 'F', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (14, 3, 'S', '1600', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (15, 3, 'Su', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (16, 3, 'M', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (17, 3, 'T', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (18, 3, 'W', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (19, 3, 'Tr', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (20, 3, 'F', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (21, 4, 'S', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (22, 4, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (23, 4, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (24, 4, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (25, 4, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (26, 4, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (27, 4, 'S', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (28, 5, 'T', '1600', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (29, 5, 'W', '1600', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (30, 5, 'Tr', '1600', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (31, 5, 'F', '1600', '0100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (32, 5, 'S', '1600', '0100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (33, 6, 'S', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (34, 6, 'Su', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (35, 6, 'M', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (36, 6, 'T', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (37, 6, 'W', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (38, 6, 'Tr', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (39, 6, 'F', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (40, 7, 'S', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (41, 7, 'Su', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (42, 7, 'M', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (43, 7, 'T', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (44, 7, 'W', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (45, 7, 'F', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (46, 7, 'S', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (47, 8, 'Su', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (48, 8, 'M', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (49, 8, 'T', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (50, 8, 'W', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (51, 8, 'Tr', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (52, 8, 'F', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (53, 8, 'S', '1000', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (54, 9, 'S', '0900', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (55, 9, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (56, 9, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (57, 9, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (58, 9, 'Tr', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (59, 9, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (60, 9, 'S', '0900', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (61, 10, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (62, 10, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (63, 10, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (64, 10, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (65, 10, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (66, 10, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (67, 10, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (68, 12, 'S', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (69, 12, 'Su', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (70, 12, 'M', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (71, 12, 'T', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (72, 12, 'W', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (73, 12, 'Tr', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (74, 12, 'F', '0800', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (75, 13, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (76, 13, 'Su', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (77, 13, 'M', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (78, 13, 'T', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (79, 13, 'W', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (80, 13, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (81, 13, 'F', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (82, 14, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (83, 14, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (84, 14, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (85, 14, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (86, 14, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (87, 14, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (88, 14, 'F', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (89, 15, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (90, 15, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (91, 15, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (92, 15, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (93, 15, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (94, 15, 'F', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (95, 16, 'S', '1000', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (96, 16, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (97, 16, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (98, 16, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (99, 16, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (100, 16, 'S', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (101, 17, 'S', '0600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (102, 17, 'Su', '0600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (103, 17, 'M', '0600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (104, 17, 'T', '0600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (105, 17, 'W', '0600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (106, 17, 'F', '0700', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (107, 17, 'S', '0700', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (108, 18, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (109, 18, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (110, 18, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (111, 18, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (112, 18, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (113, 18, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (114, 19, 'S', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (115, 19, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (116, 19, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (117, 19, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (118, 19, 'Tr', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (119, 19, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (120, 19, 'S', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (121, 20, 'Su', '1100', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (122, 20, 'M', '1100', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (123, 20, 'T', '1100', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (124, 20, 'W', '1100', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (125, 20, 'Tr', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (126, 20, 'F', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (127, 21, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (128, 21, 'Su', '1500', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (129, 21, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (130, 21, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (131, 21, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (132, 21, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (133, 21, 'F', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (134, 22, 'Su', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (135, 22, 'M', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (136, 22, 'T', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (137, 22, 'W', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (138, 22, 'Tr', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (139, 22, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (140, 22, 'S', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (141, 23, 'S', '1700', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (142, 23, 'Su', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (143, 23, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (144, 23, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (145, 23, 'Tr', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (146, 23, 'F', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (147, 24, 'S', '1600', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (148, 24, 'M', '1600', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (149, 24, 'T', '1600', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (150, 24, 'W', '1600', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (151, 24, 'Tr', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (152, 24, 'F', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (153, 25, 'S', '1000', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (154, 25, 'Su', '1100', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (155, 25, 'M', '1100', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (156, 25, 'T', '1100', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (157, 25, 'W', '1100', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (158, 25, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (159, 25, 'F', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (160, 26, 'S', '0900', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (161, 26, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (162, 26, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (163, 26, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (164, 26, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (165, 26, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (166, 26, 'F', '0900', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (167, 27, 'S', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (168, 27, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (169, 27, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (170, 27, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (171, 27, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (172, 27, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (173, 27, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (174, 28, 'S', '1000', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (175, 28, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (176, 28, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (177, 28, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (178, 28, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (179, 28, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (180, 28, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (181, 29, 'S', '1000', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (182, 29, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (183, 29, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (184, 29, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (185, 29, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (186, 29, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (187, 29, 'F', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (188, 30, 'S', '1000', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (189, 30, 'Su', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (190, 30, 'M', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (191, 30, 'T', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (192, 30, 'W', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (193, 30, 'Tr', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (194, 30, 'F', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (195, 31, 'S', '1500', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (196, 31, 'Su', '1500', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (197, 31, 'M', '1500', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (198, 31, 'T', '1500', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (199, 31, 'W', '1500', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (200, 31, 'Tr', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (201, 31, 'F', '1500', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (202, 32, 'S', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (203, 32, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (204, 32, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (205, 32, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (206, 32, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (207, 32, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (208, 32, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (209, 33, 'Su', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (210, 33, 'M', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (211, 33, 'T', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (212, 33, 'W', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (213, 33, 'Tr', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (214, 33, 'F', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (215, 34, 'Su', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (216, 34, 'M', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (217, 34, 'T', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (218, 34, 'W', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (219, 34, 'Tr', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (220, 34, 'F', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (221, 34, 'S', '1500', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (222, 35, 'S', '1000', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (223, 35, 'Su', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (224, 35, 'M', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (225, 35, 'T', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (226, 35, 'W', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (227, 35, 'Tr', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (228, 35, 'F', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (229, 36, 'S', '1030', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (230, 36, 'Su', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (231, 36, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (232, 36, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (233, 36, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (234, 36, 'Tr', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (235, 36, 'F', '1030', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (236, 37, 'S', '1000', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (237, 37, 'Su', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (238, 37, 'M', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (239, 37, 'T', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (240, 37, 'W', '1600', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (241, 37, 'F', '1600', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (242, 37, 'S', '1000', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (243, 38, 'S', '1300', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (244, 38, 'Su', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (245, 38, 'M', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (246, 38, 'T', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (247, 38, 'W', '1600', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (248, 38, 'F', '1600', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (249, 38, 'S', '1200', '0100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (250, 39, 'S', '0800', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (251, 39, 'Su', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (252, 39, 'M', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (253, 39, 'T', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (254, 39, 'W', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (255, 39, 'Tr', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (256, 39, 'F', '0800', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (257, 40, 'Su', '1000', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (258, 40, 'M', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (259, 40, 'T', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (260, 40, 'W', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (261, 40, 'Tr', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (262, 40, 'F', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (263, 40, 'S', '1000', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (264, 41, 'Su', '1000', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (265, 41, 'M', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (266, 41, 'T', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (267, 41, 'W', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (268, 41, 'Tr', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (269, 41, 'F', '1100', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (270, 41, 'S', '1000', '0200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (271, 42, 'S', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (272, 42, 'Su', '0800', '1430');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (273, 42, 'M', '0800', '1430');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (274, 42, 'T', '0800', '1430');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (275, 42, 'W', '0800', '1430');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (276, 42, 'Tr', '0800', '1430');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (277, 42, 'F', '0700', '1500');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (278, 43, 'S', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (279, 43, 'Su', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (280, 43, 'M', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (281, 43, 'T', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (282, 43, 'W', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (283, 43, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (284, 43, 'F', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (285, 44, 'S', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (286, 44, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (287, 44, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (288, 44, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (289, 44, 'W', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (290, 44, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (291, 44, 'F', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (292, 45, 'S', '1700', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (293, 45, 'Su', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (294, 45, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (295, 45, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (296, 45, 'W', '1700', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (297, 45, 'F', '1700', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (298, 45, 'S', '1700', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (299, 46, 'S', '1130', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (300, 46, 'Su', '1130', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (301, 46, 'M', '1130', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (302, 46, 'T', '1130', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (303, 46, 'W', '1130', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (304, 46, 'Tr', '1130', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (305, 46, 'F', '1130', '2230');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (306, 47, 'S', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (307, 47, 'Su', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (308, 47, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (309, 47, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (310, 47, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (311, 47, 'Tr', '1700', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (312, 47, 'F', '1700', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (313, 48, 'S', '1000', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (314, 48, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (315, 48, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (316, 48, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (317, 48, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (318, 48, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (319, 48, 'F', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (320, 49, 'S', '1030', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (321, 49, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (322, 49, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (323, 49, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (324, 49, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (325, 49, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (326, 49, 'F', '1030', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (327, 50, 'S', '1000', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (328, 50, 'Su', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (329, 50, 'M', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (330, 50, 'T', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (331, 50, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (332, 50, 'Tr', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (333, 50, 'F', '1000', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (334, 51, 'S', '1700', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (335, 51, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (336, 51, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (337, 51, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (338, 51, 'Tr', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (339, 51, 'F', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (340, 52, 'S', '0900', '1800');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (341, 52, 'M', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (342, 52, 'T', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (343, 52, 'W', '1100', '2130');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (344, 52, 'Tr', '0900', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (345, 52, 'F', '0900', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (346, 53, 'S', '0900', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (347, 53, 'Su', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (348, 53, 'M', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (349, 53, 'T', '1100', '2300');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (350, 53, 'Tr', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (351, 53, 'F', '1100', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (352, 53, 'S', '0900', '0000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (353, 54, 'S', '1700', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (354, 54, 'Su', '1100', '1400');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (355, 54, 'Su', '1700', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (356, 54, 'M', '1100', '1400');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (357, 54, 'M', '1700', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (358, 54, 'T', '1100', '1400');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (359, 54, 'T', '1700', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (360, 54, 'W', '1100', '1400');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (361, 54, 'W', '1700', '2000');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (362, 54, 'Tr', '1100', '1400');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (363, 54, 'Tr', '1700', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (364, 54, 'F', '1700', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (365, 55, 'S', '0900', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (366, 55, 'Su', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (367, 55, 'M', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (368, 55, 'T', '1100', '2100');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (369, 55, 'W', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (370, 55, 'Tr', '1100', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (371, 55, 'F', '0900', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (372, 56, 'S', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (373, 56, 'M', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (374, 56, 'T', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (375, 56, 'W', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (376, 56, 'Tr', '1700', '2200');
INSERT INTO Hours (id, location_id, weekday, open_time, close_time) VALUES (377, 56, 'F', '1700', '2200');

INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (1, 1, 39.7594, -104.986, '2620 Walnut St, Denver, CO 80205, USA', null, null, null, '(720) 573-8992', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (2, 2, 39.7493, -104.999, '1515 Market St, Denver, CO 80202, USA', null, null, null, '(303) 571-0011', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (3, 3, 39.7175, -104.953, '3000 E. First Ave., Denver, CO 80206, USA', null, null, null, '(303) 214-6474', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (4, 4, 39.6933, -104.987, '1294 S Broadway, Denver, CO 80210, USA', null, null, null, '(303) 778-1294', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (5, 5, 39.7127, -104.987, '218 S Broadway, Denver, CO 80209, USA', null, null, null, '(303) 778-8454', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (6, 6, 40.0173, -105.259, '2720 Canyon Blvd, Boulder, CO 80302, USA', null, null, null, '(303) 440-2903', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (7, 9, 39.7622, -105.013, '2227 W 32nd Ave, Denver, CO 80211, USA', null, null, null, '(720) 668-8506', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (8, 11, 39.777, -105.035, '4403 Lowell Blvd, Denver, CO 80211, USA', null, null, null, '(303) 455-9733', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (9, 12, 39.7108, -104.974, '305 S Downing St, Denver, CO 80209, USA', null, null, null, '(303) 733-3923', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (10, 13, 39.7195, -104.957, '2625 E 2nd Ave, Denver, CO 80206, USA', null, null, null, '(303) 333-2462', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (11, 14, 39.743, -104.981, '450 450 E 17th Ave #110, Denver, CO 80203, USA', null, null, null, '(303) 927-6804', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (12, 15, 39.7578, -105.007, '1644 Platte St, Denver, CO 80202, USA', null, null, null, '(303) 455-3084', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (13, 16, 39.7093, -105.076, '3216, 7167 W Alaska Dr, Denver, CO 80226, USA', null, null, null, '(303) 953-1121', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (14, 19, 39.7349, -104.988, '1147 Broadway Street #101, Denver, CO 80203, USA', null, null, null, '(720) 390-5046', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (15, 20, 39.7555, -104.99, '2233 Larimer St, Denver, CO 80205, USA', null, null, null, '(303) 296-2750', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (16, 21, 39.7592, -105.008, '1691 Central St, Denver, CO 80211, USA', null, null, null, '(303) 477-4582', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (17, 23, 39.7455, -104.997, '1401 Curtis Street, Denver, CO 80202, USA', null, null, null, '(303) 825-6500', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (18, 24, 39.7707, -104.995, '3901 Fox St, Denver, CO 80216, USA', null, null, null, '(303) 455-9666', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (19, 25, 39.769, -105.001, '1200 W 38th Ave, Denver, CO 80211, USA', null, null, null, '(720) 619-3337', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (20, 27, 39.7309, -104.986, '955 Lincoln St D, Denver, CO 80203, USA', null, null, null, '(720) 253-1244', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (21, 28, 39.7434, -104.969, '1475 E 17th Ave, Denver, CO 80218, USA', null, null, null, '(303) 386-3509', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (22, 31, 39.6814, -104.921, '1950 S Holly St, Denver, CO 80222, USA', null, null, null, '(303) 955-4904', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (23, 32, 39.767, -104.974, '3510 Larimer St, Denver, CO 80205, USA', null, null, null, '(303) 248-3497', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (24, 33, 39.762, -105.039, '3940 W 32nd Ave, Denver, CO 80212, USA', null, null, null, '(303) 963-5931', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (25, 34, 39.7691, -105.011, '3760 Tejon St, Denver, CO 80211, USA', null, null, null, '(303) 455-9852', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (26, 36, 39.7213, -104.953, '300 Fillmore St, Denver, CO 80206, USA', null, null, null, '(720) 749-4158', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (27, 39, 39.7537, -104.999, '1747 Wynkoop St, Denver, CO 80202, USA', null, null, null, '(303) 446-2337', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (28, 40, 39.7435, -104.969, '1700 Humboldt St, Denver, CO 80218, USA', null, null, null, '(303) 813-1700', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (29, 41, 39.7542, -104.991, '2124 Larimer St, Denver, CO 80205, USA', null, null, null, '(303) 296-2600', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (30, 44, 39.7056, -104.939, '650 S Colorado Blvd, Glendale, CO 80246, USA', null, null, null, '(303) 756-6449', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (31, 45, 39.7404, -104.929, '5007 E Colfax Ave, Denver, CO 80220, USA', null, null, null, '(303) 333-5007', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (32, 50, 39.7254, -104.983, '330 E 6th Ave, Denver, CO 80203, USA', null, null, null, '(303) 871-9777', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (33, 52, 39.7345, -104.991, '1135 Bannock St, Denver, CO 80204, USA', null, null, null, '(303) 825-1995', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (34, 53, 39.7622, -105.011, '3431, 3200 Tejon St, Denver, CO 80211, USA', null, null, null, '(303) 927-6334', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (35, 54, 39.7592, -105.011, '1575 Boulder St, Denver, CO 80211, USA', null, null, null, '(720) 570-8686', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (36, 56, 39.759, -105.011, '6415, 1575 Boulder St A, Denver, CO 80211, USA', null, null, null, '(720) 512-4168', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (37, 60, 39.7271, -104.985, '696 Sherman St, Denver, CO 80203, USA', null, null, null, '(303) 593-2554', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (38, 61, 39.759, -105.011, '1560 Boulder St, Denver, CO 80211, USA', null, null, null, '(720) 372-7100', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (39, 65, 39.7447, -104.969, '1420 E 18th Ave, Denver, CO 80218, USA', null, null, null, '(303) 954-0877', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (40, 68, 39.7398, -104.981, '504 E Colfax Ave, Denver, CO 80203, USA', null, null, null, '(303) 832-4840', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (41, 70, 39.7616, -105.01, '2715 17th St #103, Denver, CO 80211, USA', null, null, null, '(720) 638-0020', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (42, 71, 39.7693, -105.041, '4140 W 38th Ave, Denver, CO 80212, USA', null, null, null, '(303) 455-3132', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (43, 72, 39.7761, -105.034, '4262 Lowell Blvd, Denver, CO 80211, USA', null, null, null, '(303) 477-3000', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (44, 74, 39.7444, -104.988, '321 17th St, Denver, CO 80202, USA', null, null, null, '(303) 297-3111', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (45, 75, 39.7494, -104.998, '1550 Market St, Denver, CO 80202, USA', null, null, null, '(720) 597-8010', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (46, 76, 39.7619, -105.035, '3600 W 32nd Ave, Denver, CO 80211, USA', null, null, null, '(720) 855-0888', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (47, 77, 39.7592, -105.012, '2930 Umatilla St, Denver, CO 80211, USA', null, null, null, '(303) 955-8741', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (48, 79, 39.7356, -104.946, '1222 Madison St, Denver, CO 80206, USA', null, null, null, '(303) 736-2260', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (49, 80, 39.7473, -105.0, '1400 Larimer St, Denver, CO 80202, USA', null, null, null, '(720) 946-1433', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (50, 82, 39.7431, -104.979, '630 E 17th Ave, Denver, CO 80203, USA', null, null, null, '(303) 861-2820', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (51, 84, 39.7512, -104.933, '4645 E 23rd Ave, Denver, CO 80207, USA', null, null, null, '(303) 377-1914', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (52, 85, 39.7534, -104.989, '2191 Arapahoe St, Denver, CO 80205, USA', null, null, null, '(303) 997-9911', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (53, 87, 39.6787, -104.974, '1135 E Evans Ave, Denver, CO 80210, USA', null, null, null, '(720) 961-0320', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (54, 88, 39.6094, -104.958, '2500 E Orchard Rd, Greenwood Village, CO 80121, USA', null, null, null, '(303) 730-2152', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (55, 90, 39.7539, -105.002, '1650 Wewatta St, Denver, CO 80202, USA', null, null, null, '(720) 274-0650', null, null);
INSERT INTO Locations (id, bus_id, lat, lon, address, loc_city, loc_state, neighborhood, phone, active, perm_closed) VALUES (56, 93, 39.7435, -104.969, '1702 Humboldt St, Denver, CO 80218, USA', null, null, null, '(303) 862-5323', null, null);

